### ISSUE TITLE
Enhancement Please add more curios to Charm slots

### ISSUE THREAD

**Issue by AbsorbingSafe11** [Octo-Studios/rar-compat#1]
In both Relics and Artifacts there are very few charms making stuff that increases charm amount nearly worthless (the Relics belts are a good example, especially the leather belt)

Several of the belts in Artifacts (now amulets of the latest patch) have far less useful or far more niche effects that make them less usable in a normal game (like the Universal Attractor can't compete with the scarf that gives bonus Fortune)

Changing the lesser used and weaker curios to use the Charm slot (like the Whoopie Cushion, Universal Attracter and a few more) allows more players to use and level them up without a significant increase in player power as well as to increase usability of the Relics belts (also it makes model sense in that all the Relics belts go on the player in a belt position)

**Comment by AbsorbingSafe11** [comment]
I haven't used Github very much so I couldn't figure out how to add any labels to this myself (otherwise i would have added the Enhancement label)

**Comment by SSKirillSS** [comment]
Starting from patch 1.21-0.6, most items that were previously equipped in the belt slot are now equipped in the charm slot. Some items, like the whoopee cushion, are equipped in other slots despite their relative "uselessness" in the game, because in the original concept by the author of Artifacts, their models are positioned in areas different from the belt.
